import { Copy, ExternalLink, FileWarning, Monitor, Moon, RefreshCw, RotateCcw, Sun } from "lucide-react";
import { useEffect, useState } from "react";
import { useI18n } from "../lib/i18n";
import type { CleanMode, ContextMenuStatus } from "../types";
import { useUpdate } from "../contexts/UpdateContext";
import { useTheme } from "../contexts/ThemeContext";
import { LOCALES, type Locale } from "../lib/locales";

interface SettingsPageProps { mode: CleanMode; onModeChange: (mode: CleanMode) => void; preserveTimestamps: boolean; onPreserveTimestampsChange: (value: boolean) => void; preserveOrientation: boolean; onPreserveOrientationChange: (value: boolean) => void; preserveColorProfile: boolean; onPreserveColorProfileChange: (value: boolean) => void }

export default function SettingsPage({ mode, onModeChange, preserveTimestamps, onPreserveTimestampsChange, preserveOrientation, onPreserveOrientationChange, preserveColorProfile, onPreserveColorProfileChange }: SettingsPageProps) {
  const [contextMenu, setContextMenu] = useState<ContextMenuStatus>();
  const [busy, setBusy] = useState(false);
  const { locale, setLocale, text } = useI18n();
  const update = useUpdate();
  const theme = useTheme();
  useEffect(() => { void import("@tauri-apps/api/core").then(({ invoke }) => invoke<ContextMenuStatus>("get_context_menu_status")).then(setContextMenu).catch(() => undefined); }, []);
  async function toggleContextMenu() {
    if (!contextMenu?.available) return;
    setBusy(true);
    try { const { invoke } = await import("@tauri-apps/api/core"); setContextMenu(await invoke<ContextMenuStatus>("set_context_menu_enabled", { enabled: !contextMenu.enabled })); }
    finally { setBusy(false); }
  }
  return (
    <section className="secondary-page">
      <div className="page-heading"><div><h1>{text("设置", "Settings")}</h1><p>{text("设置会自动保存在本机。", "Settings are saved locally.")}</p></div></div>
      <div className="settings-card"><div className="setting-row"><div><h2>{text("界面语言", "Language")}</h2><p>{text("切换后立即生效。", "Changes apply immediately.")}</p></div><div className="locale-switch"><select aria-label={text("界面语言", "Language")} value={locale} onChange={(event) => setLocale(event.target.value as Locale)}>{LOCALES.map((option) => <option key={option.code} value={option.code}>{option.nativeName}</option>)}</select></div></div></div>
      <div className="settings-card"><h2>{text("界面主题", "Appearance")}</h2><p>{text("跟随系统，或固定使用浅色/深色主题。", "Follow the system or keep a fixed light or dark theme.")}</p><div className="theme-choices"><button className={theme.mode === "system" ? "selected" : ""} type="button" onClick={() => theme.setMode("system")}><Monitor size={17}/>{text("跟随系统", "System")}</button><button className={theme.mode === "light" ? "selected" : ""} type="button" onClick={() => theme.setMode("light")}><Sun size={17}/>{text("浅色", "Light")}</button><button className={theme.mode === "dark" ? "selected" : ""} type="button" onClick={() => theme.setMode("dark")}><Moon size={17}/>{text("深色", "Dark")}</button></div></div>
      <div className="settings-card"><h2>{text("默认输出方式", "Default output mode")}</h2><p>{text("每次添加新文件时使用的默认策略。", "The default strategy for newly added files.")}</p><div className="settings-choices"><button className={mode === "copy" ? "selected" : ""} type="button" onClick={() => onModeChange("copy")}><Copy size={18}/><span><strong>{text("保存为安全副本", "Save a safe copy")}</strong><small>{text("保留原文件，生成 .cleaned 副本", "Keep the original and create a .cleaned copy")}</small></span></button><button className={mode === "replace" ? "selected" : ""} type="button" onClick={() => onModeChange("replace")}><FileWarning size={18}/><span><strong>{text("替换并备份", "Replace with backup")}</strong><small>{text("先创建 .bak，再原子替换原文件", "Create .bak, then atomically replace the original")}</small></span></button></div></div>
      <div className="settings-card"><h2>{text("保真选项", "Fidelity options")}</h2><p>{text("只保留显示和文件管理所需的信息，不保留 GPS、作者或来源元数据。", "Keep only information needed for display and file management, never GPS, author, or provenance metadata.")}</p><div className="fidelity-options"><label><input type="checkbox" checked={preserveOrientation} onChange={(event) => onPreserveOrientationChange(event.target.checked)}/><span><strong>{text("保留 JPEG 显示方向", "Preserve JPEG display orientation")}</strong><small>{text("把方向重建为最小 EXIF 段，其余 EXIF/GPS 仍全部移除。", "Rebuilds a minimal orientation-only EXIF segment; all other EXIF/GPS data is removed.")}</small></span></label><label><input type="checkbox" checked={preserveColorProfile} onChange={(event) => onPreserveColorProfileChange(event.target.checked)}/><span><strong>{text("图片", "Images")} · ICC / sRGB</strong></span></label><label><input type="checkbox" checked={preserveTimestamps} onChange={(event) => onPreserveTimestampsChange(event.target.checked)}/><span><strong>{text("保留访问和修改时间", "Preserve access and modification times")}</strong><small>{text("关闭后，输出文件使用清理时的时间。", "When disabled, output files use the cleanup time.")}</small></span></label></div></div>
      <div className="settings-card"><div className="setting-row"><div><h2>{text("Windows 右键菜单", "Windows context menu")}</h2><p>{contextMenu ? text(contextMenu.detail, contextMenu.available ? (contextMenu.enabled ? "Enabled for supported file types. On Windows 11, use Show more options." : "Enable the File Explorer command for supported types. On Windows 11, it appears under Show more options.") : "Context-menu integration is available on Windows only.") : text("正在检测资源管理器集成…", "Checking File Explorer integration…")}</p></div><button type="button" disabled={!contextMenu?.available || busy} onClick={() => void toggleContextMenu()}>{busy ? text("处理中…", "Working…") : contextMenu?.enabled ? text("停用", "Disable") : text("启用", "Enable")}</button></div></div>
      <div className="settings-card update-card">
        <div className="setting-row"><div><h2>{text("版本更新", "Software updates")}</h2><p>{update.status === "checking" ? text("正在检查 GitHub 正式版本…", "Checking the latest stable GitHub release…") : update.status === "available" ? text(`当前 ${update.currentVersion}，可更新到 ${update.info?.availableVersion}。`, `Version ${update.currentVersion} is installed; ${update.info?.availableVersion} is available.`) : update.status === "current" ? text(`当前 ${update.currentVersion}，已经是最新版。`, `Version ${update.currentVersion} is up to date.`) : update.status === "error" ? text(`检查失败：${update.error}`, `Update check failed: ${update.error}`) : text("仅连接 GitHub Releases，不发送文件或使用情况。", "Checks GitHub Releases only; no files or usage data are sent.")}</p></div><div className="settings-actions"><button type="button" disabled={update.status === "checking"} onClick={() => void update.checkUpdate()}><RefreshCw size={14}/>{text("检查更新", "Check now")}</button>{update.status === "available" ? <button type="button" onClick={() => void update.openRelease()}><ExternalLink size={14}/>{text("下载新版本", "Download")}</button> : null}</div></div>
        <label className="update-toggle"><input type="checkbox" checked={update.autoCheckEnabled} onChange={(event) => update.setAutoCheckEnabled(event.target.checked)}/><span><strong>{text("启动后自动检查", "Check automatically after launch")}</strong><small>{text("关闭后 MetaClean 将保持完全离线，直到你手动检查。", "When disabled, MetaClean remains fully offline until you check manually.")}</small></span></label>
      </div>
      <div className="settings-card"><h2>{text("安全保证", "Safety guarantees")}</h2><div className="safety-grid"><span><RotateCcw size={16}/>{text("替换模式始终备份", "Replacement always creates a backup")}</span><span>{text("单文件最大 256 MiB", "256 MiB maximum per file")}</span><span>{text("拒绝写入符号链接", "Refuses symlink writes")}</span><span>{text("输出采用临时文件原子替换", "Atomic temporary-file output")}</span></div></div>
    </section>
  );
}
